version: '3.2'
services:
  my-app:
    image: app:v1.2
    build:
      context: /client
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    volumes:
      - app:/frontend

volumes:
  app: {}