version: '3.2'
services:
  frontend:
    image: johannsbbd/bbd-grad-period-tracker-frontend:v1.1
    ports:
      - 8080:3000
  
  backend:
    image: johannsbbd/bbd-grad-period-tracker-backend:v1.1
    ports:
      - 3000:3000